import { readdirSync, readFileSync, writeFileSync } from "node:fs";
import { join, basename } from "node:path";

const webRoot = new URL("..", import.meta.url).pathname;
const iconsDir = join(webRoot, "node_modules", "lucide-static", "icons");
const outFile = join(webRoot, "features", "templates", "icons-data.generated.ts");

const pkg = JSON.parse(
  readFileSync(join(webRoot, "node_modules", "lucide-static", "package.json"), "utf8")
);

const icons = readdirSync(iconsDir)
  .filter((file) => file.endsWith(".svg"))
  .sort()
  .map((file) => {
    const raw = readFileSync(join(iconsDir, file), "utf8");
    const openTagEnd = raw.indexOf(">", raw.indexOf("<svg"));
    const inner = raw
      .slice(openTagEnd + 1)
      .replace(/<\/svg>\s*$/, "")
      .replace(/\s+/g, " ")
      .trim();
    return { name: basename(file, ".svg"), svg: inner };
  });

const lines = [
  `// Generated by scripts/generate-icons.mjs from lucide-static v${pkg.version}. DO NOT EDIT.`,
  "",
  "export interface GeneratedIcon {",
  "  name: string;",
  "  svg: string;",
  "}",
  "",
  "export const GENERATED_ICONS: GeneratedIcon[] = [",
  ...icons.map((icon) => `  { name: ${JSON.stringify(icon.name)}, svg: ${JSON.stringify(icon.svg)} },`),
  "];",
  "",
  "export const GENERATED_ICON_MAP: Record<string, string> = {",
  ...icons.map((icon) => `  ${JSON.stringify(icon.name)}: ${JSON.stringify(icon.svg)},`),
  "};",
  "",
];

writeFileSync(outFile, lines.join("\n"));
console.log(`Wrote ${icons.length} icons to ${outFile}`);
