import { readdirSync, readFileSync, writeFileSync } from "node:fs";
import { join, basename } from "node:path";

const webRoot = new URL("..", import.meta.url).pathname;
const iconsDir = join(webRoot, "node_modules", "lucide-static", "icons");
const outFile = join(webRoot, "features", "templates", "icons-data.generated.ts");
const uiOutFile = join(webRoot, "features", "templates", "ui-icons-data.generated.ts");

const uiIconNames = new Set([
  "arrow-left",
  "arrow-up-right",
  "atom",
  "blocks",
  "box-select",
  "calendar-plus",
  "check",
  "chevron-down",
  "circle-alert",
  "circle-check",
  "circle-help",
  "clock",
  "clock-3",
  "cloud-off",
  "code-2",
  "code-xml",
  "copy",
  "database",
  "eye",
  "file-code",
  "file-down",
  "file-json",
  "globe",
  "grid-3x3",
  "grip-vertical",
  "image-down",
  "inbox",
  "info",
  "keyboard",
  "layers-2",
  "layout-template",
  "loader-circle",
  "lock",
  "pencil",
  "plus",
  "printer",
  "rectangle-horizontal",
  "ruler",
  "save",
  "settings",
  "sparkles",
  "square-check",
  "trash-2",
  "triangle",
  "triangle-alert",
  "wand-sparkles",
  "x",
]);

const pkg = JSON.parse(
  readFileSync(join(webRoot, "node_modules", "lucide-static", "package.json"), "utf8")
);

const icons = readdirSync(iconsDir)
  .filter((file) => file.endsWith(".svg"))
  .sort()
  .map((file) => {
    const raw = readFileSync(join(iconsDir, file), "utf8");
    const openTagEnd = raw.indexOf(">", raw.indexOf("<svg"));
    const inner = raw
      .slice(openTagEnd + 1)
      .replace(/<\/svg>\s*$/, "")
      .replace(/\s+/g, " ")
      .trim();
    return { name: basename(file, ".svg"), svg: inner };
  });

const lines = [
  `// Generated by scripts/generate-icons.mjs from lucide-static v${pkg.version}. DO NOT EDIT.`,
  "",
  "export interface GeneratedIcon {",
  "  name: string;",
  "  svg: string;",
  "}",
  "",
  "export const GENERATED_ICONS: GeneratedIcon[] = [",
  ...icons.map((icon) => `  { name: ${JSON.stringify(icon.name)}, svg: ${JSON.stringify(icon.svg)} },`),
  "];",
  "",
];

writeFileSync(outFile, lines.join("\n"));
const uiIcons = icons.filter((icon) => uiIconNames.has(icon.name));
if (uiIcons.length !== uiIconNames.size) {
  const generatedNames = new Set(uiIcons.map((icon) => icon.name));
  const missing = [...uiIconNames].filter((name) => !generatedNames.has(name));
  throw new Error(`Missing UI icons: ${missing.join(", ")}`);
}
const uiLines = [
  `// Generated by scripts/generate-icons.mjs from lucide-static v${pkg.version}. DO NOT EDIT.`,
  "",
  "export const UI_ICON_MAP: Record<string, string> = {",
  ...uiIcons.map((icon) => `  ${JSON.stringify(icon.name)}: ${JSON.stringify(icon.svg)},`),
  "};",
  "",
];
writeFileSync(uiOutFile, uiLines.join("\n"));
console.log(`Wrote ${icons.length} design icons and ${uiIcons.length} UI icons`);
