"use client";

import { useRef, useState } from "react";
import { codeFileName, downloadTextFile } from "@/features/templates/downloads";
import PreviewExportActions from "./preview-export-actions";

type Tab = "preview" | "html" | "react" | "angular";

export default function CodeOutput({
  title,
  html,
  previewHtml,
  reactCode,
  angularCode,
}: {
  title: string;
  html: string;
  previewHtml: string[];
  reactCode: string;
  angularCode: string;
}) {
  const previewRef = useRef<HTMLDivElement>(null);
  const [tab, setTab] = useState<Tab>("preview");
  const [copied, setCopied] = useState(false);

  const code =
    tab === "html" ? html : tab === "react" ? reactCode : angularCode;

  async function handleCopy() {
    await navigator.clipboard.writeText(code);
    setCopied(true);
    setTimeout(() => setCopied(false), 1500);
  }

  function handleDownloadCode() {
    if (tab === "preview") return;
    downloadTextFile(code, codeFileName(title, tab));
  }

  return (
    <div className="overflow-hidden rounded-2xl border border-zinc-200 bg-white shadow-sm dark:border-zinc-800 dark:bg-zinc-900">
      <div className="flex flex-wrap items-center justify-between gap-2 border-b border-zinc-200 px-4 py-2 dark:border-zinc-800">
        <div className="flex flex-wrap gap-1">
          {(["preview", "html", "react", "angular"] as const).map((t) => (
            <button
              key={t}
              type="button"
              onClick={() => setTab(t)}
              className={
                "rounded-lg px-3 py-1.5 text-xs font-medium capitalize transition-colors " +
                (tab === t
                  ? "bg-zinc-100 text-zinc-900 dark:bg-zinc-800 dark:text-zinc-50"
                  : "text-zinc-500 hover:text-zinc-900 dark:text-zinc-400 dark:hover:text-zinc-50")
              }
            >
              {t}
            </button>
          ))}
        </div>
        <div className="flex gap-1">
          {tab === "preview" ? (
            <PreviewExportActions title={title} previewRef={previewRef} />
          ) : (
            <>
              <button
                type="button"
                onClick={handleCopy}
                className="rounded-lg border border-zinc-300 px-3 py-1.5 text-xs font-medium transition-colors hover:bg-zinc-50 dark:border-zinc-700 dark:hover:bg-zinc-800"
              >
                {copied ? "Copied!" : "Copy"}
              </button>
              <button
                type="button"
                onClick={handleDownloadCode}
                className="rounded-lg border border-zinc-300 px-3 py-1.5 text-xs font-medium transition-colors hover:bg-zinc-50 dark:border-zinc-700 dark:hover:bg-zinc-800"
              >
                Download file
              </button>
            </>
          )}
        </div>
      </div>

      {tab === "preview" ? (
        <div className="max-h-[32rem] overflow-auto bg-zinc-50 p-4 dark:bg-zinc-950/40">
          {/* Generated by our own codegen from editor inputs — all values escaped at generation time */}
          <div ref={previewRef}>
            <div data-template-preview-batch className="inline-flex flex-col gap-4 bg-white">
              {previewHtml.map((preview, index) => (
                <div
                  key={index}
                  data-template-preview-card
                  dangerouslySetInnerHTML={{ __html: preview }}
                />
              ))}
            </div>
          </div>
        </div>
      ) : (
        <pre className="max-h-96 overflow-auto p-4 text-xs leading-relaxed text-zinc-700 dark:text-zinc-300">
          <code>{code}</code>
        </pre>
      )}
    </div>
  );
}
