"use client";

import { useState } from "react";

type Tab = "preview" | "html" | "react" | "angular";

export default function CodeOutput({
  html,
  reactCode,
  angularCode,
}: {
  html: string;
  reactCode: string;
  angularCode: string;
}) {
  const [tab, setTab] = useState<Tab>("preview");
  const [copied, setCopied] = useState(false);

  const code =
    tab === "html" ? html : tab === "react" ? reactCode : angularCode;

  async function handleCopy() {
    await navigator.clipboard.writeText(code);
    setCopied(true);
    setTimeout(() => setCopied(false), 1500);
  }

  return (
    <div className="overflow-hidden rounded-2xl border border-zinc-200 bg-white shadow-sm dark:border-zinc-800 dark:bg-zinc-900">
      <div className="flex items-center justify-between border-b border-zinc-200 px-4 py-2 dark:border-zinc-800">
        <div className="flex gap-1">
          {(["preview", "html", "react", "angular"] as const).map((t) => (
            <button
              key={t}
              type="button"
              onClick={() => setTab(t)}
              className={
                "rounded-lg px-3 py-1.5 text-xs font-medium capitalize transition-colors " +
                (tab === t
                  ? "bg-zinc-100 text-zinc-900 dark:bg-zinc-800 dark:text-zinc-50"
                  : "text-zinc-500 hover:text-zinc-900 dark:text-zinc-400 dark:hover:text-zinc-50")
              }
            >
              {t}
            </button>
          ))}
        </div>
        {tab !== "preview" && (
          <button
            type="button"
            onClick={handleCopy}
            className="rounded-lg border border-zinc-300 px-3 py-1.5 text-xs font-medium transition-colors hover:bg-zinc-50 dark:border-zinc-700 dark:hover:bg-zinc-800"
          >
            {copied ? "Copied!" : "Copy"}
          </button>
        )}
      </div>

      {tab === "preview" ? (
        <div className="max-h-[32rem] overflow-auto bg-zinc-50 p-4 dark:bg-zinc-950/40">
          {/* Generated by our own codegen from editor inputs — all values escaped at generation time */}
          <div dangerouslySetInnerHTML={{ __html: html }} />
        </div>
      ) : (
        <pre className="max-h-96 overflow-auto p-4 text-xs leading-relaxed text-zinc-700 dark:text-zinc-300">
          <code>{code}</code>
        </pre>
      )}
    </div>
  );
}
