"use client";

import { useRef, useState } from "react";
import { codeFileName, downloadTextFile } from "@/features/templates/downloads";
import type { CodeLang, TemplateMetadata } from "@/features/templates/types";
import AccessibleDialog from "@/components/ui/accessible-dialog";
import { EditorIcon, EditorTooltip } from "./editor-controls";
import PreviewExportActions from "./preview-export-actions";
import SandboxedCodePreview, {
  type SandboxedCodePreviewHandle,
} from "./sandboxed-code-preview";

const CODE_TYPES: { lang: Exclude<CodeLang, "angular">; label: string; icon: string }[] = [
  { lang: "html", label: "HTML", icon: "code-xml" },
  { lang: "react", label: "React", icon: "atom" },
];

export default function PreviewDialog({
  open,
  onClose,
  title,
  mode,
  lang,
  code,
  metadata,
  previewHtml,
  html,
  react,
}: {
  open: boolean;
  onClose: () => void;
  title: string;
  mode: "wysiwyg" | "code";
  lang: CodeLang;
  code: string;
  metadata: TemplateMetadata;
  previewHtml: string[];
  html: string;
  react: string;
}) {
  const previewRef = useRef<HTMLDivElement>(null);
  const sandboxPreviewRef = useRef<SandboxedCodePreviewHandle>(null);
  const [copied, setCopied] = useState<"html" | "react" | null>(null);
  const [copyError, setCopyError] = useState<string | null>(null);

  const sandboxMode = lang === "react" ? "react" : "html";

  async function handleCopy(target: "html" | "react") {
    const source = target === "html" ? html : react;
    setCopyError(null);
    try {
      await navigator.clipboard.writeText(source);
      setCopied(target);
      setTimeout(() => setCopied(null), 1500);
    } catch (error) {
      setCopied(null);
      setCopyError(error instanceof Error ? error.message : "Could not copy the code.");
    }
  }

  function handleDownload(target: "html" | "react") {
    downloadTextFile(
      target === "html" ? html : react,
      codeFileName(title, target)
    );
  }

  return (
    <AccessibleDialog
      open={open}
      onClose={onClose}
      labelledBy="preview-dialog-title"
      panelClassName="flex max-h-[88dvh] w-full max-w-3xl flex-col overflow-hidden rounded-2xl bg-white shadow-2xl dark:bg-zinc-900"
    >
      <div className="flex items-center justify-between gap-3 border-b border-zinc-200 px-5 py-4 dark:border-zinc-800">
        <h2
          id="preview-dialog-title"
          className="flex items-center gap-2 text-base font-semibold text-zinc-900 dark:text-zinc-50"
        >
          <span className="grid size-8 place-items-center rounded-lg bg-zinc-100 text-zinc-600 dark:bg-zinc-800 dark:text-zinc-300">
            <EditorIcon name="eye" />
          </span>
          Preview
        </h2>
        <button
          type="button"
          onClick={onClose}
          aria-label="Close preview"
          className="grid size-9 place-items-center rounded-lg text-zinc-400 transition-colors hover:bg-zinc-100 hover:text-zinc-900 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-zinc-400 dark:hover:bg-zinc-800 dark:hover:text-white"
        >
          <EditorIcon name="x" />
        </button>
      </div>

      <div className="min-h-0 flex-1 overflow-auto bg-zinc-100/70 p-5 dark:bg-zinc-950/50">
        {mode === "wysiwyg" ? (
          <div className="mx-auto w-fit rounded-xl border border-zinc-200/80 bg-white/60 p-3 shadow-inner dark:border-zinc-800 dark:bg-zinc-900/50">
            {/* Generated by our own codegen from editor inputs — all values escaped at generation time */}
            <div ref={previewRef}>
              <div data-template-preview-batch className="inline-flex flex-col gap-4 bg-transparent">
                {previewHtml.map((preview, index) => (
                  <div
                    key={index}
                    data-template-preview-card
                    dangerouslySetInnerHTML={{ __html: preview }}
                  />
                ))}
              </div>
            </div>
          </div>
        ) : (
          <div className="overflow-hidden rounded-xl border border-zinc-200 bg-white dark:border-zinc-800">
            <SandboxedCodePreview
              ref={sandboxPreviewRef}
              mode={sandboxMode}
              code={code}
              metadata={metadata}
            />
          </div>
        )}
      </div>

      <div className="flex flex-wrap items-center justify-between gap-2 border-t border-zinc-200 px-4 py-3 dark:border-zinc-800">
        <div className="flex items-center gap-1 rounded-xl border border-zinc-200 p-1 dark:border-zinc-700">
          {CODE_TYPES.map((codeType) => (
            <EditorTooltip
              key={codeType.lang}
              label={copied === codeType.lang ? "Copied" : `Copy ${codeType.label} code`}
              align="right"
              placement="top"
            >
              <button
                type="button"
                onClick={() => void handleCopy(codeType.lang)}
                aria-label={copied === codeType.lang ? "Code copied" : `Copy ${codeType.label} code`}
                className="grid size-10 place-items-center rounded-lg text-zinc-500 transition-colors hover:bg-zinc-100 hover:text-zinc-950 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-zinc-400 dark:text-zinc-400 dark:hover:bg-zinc-800 dark:hover:text-white"
              >
                <EditorIcon name={copied === codeType.lang ? "check" : "copy"} />
              </button>
            </EditorTooltip>
          ))}
          {CODE_TYPES.map((codeType) => (
            <EditorTooltip
              key={codeType.lang}
              label={`Download ${codeType.label} file`}
              align="right"
              placement="top"
            >
              <button
                type="button"
                onClick={() => handleDownload(codeType.lang)}
                aria-label={`Download ${codeType.label} file`}
                className="grid size-10 place-items-center rounded-lg text-zinc-500 transition-colors hover:bg-zinc-100 hover:text-zinc-950 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-zinc-400 dark:text-zinc-400 dark:hover:bg-zinc-800 dark:hover:text-white"
              >
                <EditorIcon name="file-down" />
              </button>
            </EditorTooltip>
          ))}
        </div>

        <PreviewExportActions
          title={title}
          tooltipPlacement="top"
          previewRef={mode === "wysiwyg" ? previewRef : undefined}
          previewRenderer={
            mode === "code"
              ? (target, options) => {
                  const preview = sandboxPreviewRef.current;
                  if (!preview) return Promise.reject(new Error("Preview is not ready yet."));
                  return preview.renderImages(target, options);
                }
              : undefined
          }
        />
      </div>

      {copyError ? (
        <p
          role="alert"
          className="flex items-center gap-2 border-t border-red-200 bg-red-50 px-4 py-2 text-sm text-red-700 dark:border-red-950 dark:bg-red-950/40 dark:text-red-300"
        >
          <EditorIcon name="circle-alert" className="size-4 shrink-0" />
          {copyError}
        </p>
      ) : null}
    </AccessibleDialog>
  );
}
